name: saju_app
description: A Flutter app for fortune telling using traditional Korean Saju (Four Pillars)
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  dio: ^5.0.0
  permission_handler: ^11.0.1
  # audioplayers: ^5.2.1  # 크래시 원인으로 제거
  path_provider: ^2.1.1
  webview_flutter: ^4.7.0
  google_sign_in: 6.2.1
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.2
  share_plus: ^10.0.0
  # google_maps_flutter: ^2.5.3  # Google Maps SDK 주석
  # geolocator: ^10.1.0  # 위치 권한 주석
  # geocoding: ^2.1.1  # 주소 변환 주석

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  macos: true
  image_path: "assets/icons/zodiac_wheel_icon_256.png"

flutter_native_splash:
  color: "#1a1a2e"
  image: assets/icons/zodiac_wheel_icon_256.png
  android_12:
    image: assets/icons/zodiac_wheel_icon_256.png
    color: "#1a1a2e"
  web: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/design/
    - assets/data/
    - web/
    - web/icons/
  
